[project]
name = "sopho-scribe"
version = "0.1.0"
description = "Conversational AI interface to aid in client p-facing work using data from Microsoft 365, google products, earnings reports, and more."
authors = [
    {name = "Lily Campbell",email = "lilycampbell@uchicago.edu"},
    {name = "Xiaojing Fang", email = "xjfang@uchicago.edu"},
    {name = "Gretchen Forbush", email = "forbug@uchicago.edu"},
    {name = "Stepan Ochodek", email = "sochodek@uchicago.edu"},
    {name = "Alen Pavlovic", email = "apavlovic@uchicago.edu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
