FROM python:3.11.12-slim

WORKDIR /app

COPY pyproject.toml .
COPY poetry.lock .
RUN poetry install 

COPY src/agents/ ./agents/
COPY src/core/ ./core/
COPY src/memory/ ./memory/
COPY src/schema/ ./schema/
COPY src/service/ ./service/
COPY src/run_service.py .

CMD ["python", "run_service.py"]